name: Create a new release & tag commit

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'ado_express/tests/**'
    branches:
      - main

jobs:
  linux:
    name: Create a new release & tag commit
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Update script permission
        run: chmod +x .github/scripts/release.py

      # On manual workflow dispatch create new patch release
      - name: Create new patch release
        if: github.event_name == 'workflow_dispatch'
        run: .github/scripts/release.py patch
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      # On push create new minor release
      - name: Create new minor release
        if: github.event_name == 'push'
        run: .github/scripts/release.py minor
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}